install:
  - ps: cd c:\projects
  - ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
  - ps: Invoke-WebRequest https://github.com/dasher-project/dasher/files/1824036/Expat.2.2.5.zip -OutFile expat.zip
  - ps: 7z x ./expat.zip
  - ps: ls c:\projects\dasher\Src\Win32
  - ps: ls c:\projects\dasher\Src\Win32\Dasher.sln

configuration: Debug

environment:
  expat: 'c:\projects\Expat 2.2.5\'
  matrix:
    # Visual Studio 2017 Win32
    - GENERATOR: Visual Studio 15 2017
      PLATFORM: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

before_build:
  - echo Moving to Win32 folder...
  - cd c:\projects\dasher\Src\Win32

build:
  parallel: true                                                # enable MSBuild parallel builds
  project: c:\projects\dasher\Src\Win32\Dasher.sln              # path to Visual Studio solution or project
